# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VpatuQnZ-JfgT7rilr3k5aMY6DZytL_
"""

print("Hello, Python World!")

print("The number is", 4)
print("2 + 2 =", 3 + 2)

name = "Vivian"
print(f"Hello, {name}! Welcome to Python Programming")

userName = input("What is your name? ")
print(f"Hello, {userName}! Welcome to Python Programming")

# Welcome Message Generator

# Step 1: Ask for user details
name = input("What's your name? ")
hobby = input("What's your favorite hobby? ")

# Step 2: Generate a personalized welcome message
print("\n--- Welcome Message ---")
print(f"Hello, {name}! 👋")
print(f"Welcome to the world of Python Programming.")
print(f"It's great to know that you love {hobby}.")
print(f"Get ready to build something amazing today.")